Import dependence

In [33]:
import numpy as np
import random

In [42]:
def softmax(x):
    """
    Compute the softmax function for each row of the input x.

    It is crucial that this function is optimized for speed because
    it will be used frequently in later code.
    You might find numpy functions np.exp, np.sum, np.reshape,
    np.max, and numpy broadcasting useful for this task. (numpy
    broadcasting documentation:
    http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

    You should also make sure that your code works for one
    dimensional inputs (treat the vector as a row), you might find
    it helpful for your later problems.

    You must implement the optimization in problem 1(a) of the 
    written assignment!
    """
    ### YOUR CODE HERE 
    ### 根据softmax(x) = softmax(x+c) 施行x-np.max(x)后再exp防止溢出
    
    if len(x.shape) == 1 :
        exp = np.exp(x - np.max(x))
        x = exp / np.sum(exp)
    else:
        x_max = x.max(axis=1)
        if len(x_max.shape) == 1:
            x_max = x_max.reshape(x_max.shape[0],1)
        exp = np.exp(x - x_max)
        exp_sum = exp.sum(axis=1)
        if len(exp_sum.shape) == 1:
            exp_sum = exp_sum.reshape(exp_sum.shape[0],1)
        x = exp / exp_sum
    ### END YOUR CODE
    
    return x

In [43]:
def test_softmax_basic():
    """
    Some simple tests to get you started. 
    Warning: these are not exhaustive.
    """
    print("Running basic tests...")
    test1 = softmax(np.array([1,2]))
    print(test1)
    assert np.amax(np.fabs(test1 - np.array(
        [0.26894142,  0.73105858]))) <= 1e-6

    test2 = softmax(np.array([[1001,1002],[3,4]]))
    print(test2)
    assert np.amax(np.fabs(test2 - np.array(
        [[0.26894142, 0.73105858], [0.26894142, 0.73105858]]))) <= 1e-6

    test3 = softmax(np.array([[-1001,-1002]]))
    print(test3)
    assert np.amax(np.fabs(test3 - np.array(
        [0.73105858, 0.26894142]))) <= 1e-6

    print("You should verify these results!\n")

In [48]:
def test_softmax():
    """ 
    Use this space to test your softmax implementation by running:
        python q1_softmax.py 
    This function will not be called by the autograder, nor will
    your tests be graded.
    """
    print("Running your tests...")
    ### YOUR CODE HERE
    x = np.array([[2.5,2.5,3.3],[745.6,586.2,635.3],[9987.2,5243.1,6584.1],[0.254,0.364,0.894],[12.54,784.3,125.2]])
    result = softmax(x)
    print(result)
    ### END YOUR CODE 

In [49]:
test_softmax_basic()
test_softmax()

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should verify these results!

Running your tests...
[[  2.36656091e-001   2.36656091e-001   5.26687817e-001]
 [  1.00000000e+000   5.93553110e-070   1.25117669e-048]
 [  1.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  2.49205101e-001   2.78182189e-001   4.72612709e-001]
 [  0.00000000e+000   1.00000000e+000   5.70830247e-287]]
